#!/system/bin/sh
#
# Load MODULES
sleep 1
insmod /system/lib/modules/cifs.ko
insmod /system/lib/modules/fuse.ko
insmod /system/lib/modules/tun.ko
insmod /system/lib/modules/zram.ko
echo "+++ Modules Loaded +++";
